name: RGCPD4
channels:
  - conda-forge


dependencies:
  - cartopy
  - cftime
  - conda
  - cdsapi
  - ecmwf-api-client
  - eofs
  - h5py
  - hdf4
  - hdf5
  - ipython
  - jupyterlab
  - matplotlib
  - matplotlib-base
  - nbconvert
  - nbformat
  - netcdf4
  - numpy
  - pandas
  - pip
  - python>=3.8, <=3.9
#  - pytest # <- optional for pytesting
  - scikit-learn
  - scipy
  - seaborn
  - shapely
#  - spyder # <- optional Spyder IDE
  - statsmodels
  - pytables
  - xarray
  - properscoring
  - joblib # <- for parallel computing
#  - esmf # <- optional packages for regridding
#  - xesmf # <- optional packages for regridding
  - pip:
    - tigramite
prefix: /Users/semvijverberg/miniconda3/envs/RGCPD4
# If mamba has not been installed in your conda base environment, then please run:
# conda install mamba -n base -c conda-forge
# mamba env create -f environment.yml
# Tigramite also needs cython: pip install cython
# to install spyder later:
# mamba install -c conda-forge spyder
# If working on a Windows, you need to have installed the visual c++ build tools
# https://visualstudio.microsoft.com/visual-cpp-build-tools/
